### ISSUE TITLE
Need Help For Run the Project

### ISSUE THREAD

**Issue by maskmeta451** [mitmelon/gim#1]
My Application is successfully Build by following all the process. I have to run this into my browser when i try to run ->
 ->  http://localhost:5173/
 
![image](https://github.com/mitmelon/gim/assets/164132206/5703b472-0ce5-4fa9-be50-7cd5a62ed52d)

-> It shows Me error, I can't find readme also how can i run into this in Browser,
In Readme there is line -> Go to your application url and kick start it. But which one is URL I don't understand.

![image](https://github.com/mitmelon/gim/assets/164132206/295c98cc-c245-439b-9204-4cbea3e03a57)

**Comment by mitmelon** [comment]
> My Application is successfully Build by following all the process. I have to run this into my browser when i try to run -> -> http://localhost:5173/
> 
> ![image](https://private-user-images.githubusercontent.com/164132206/315274092-5703b472-0ce5-4fa9-be50-7cd5a62ed52d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDA4MDcsIm5iZiI6MTcxMzgwMDUwNywicGF0aCI6Ii8xNjQxMzIyMDYvMzE1Mjc0MDkyLTU3MDNiNDcyLTBjZTUtNGZhOS1iZTUwLTdjZDVhNjJlZDUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNTQxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTM2YzNmMDdkMGRlYzNkZWEyZWYyMzFmZWQ2OTUwYjEyMWQ1MWViNjQ1ZWQzNmRlMWUwMTljZDdjODEyZWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TVlH9kggCjWR8IwDMj4PyC_EYrQWI60GntiYSg9LwrE)
> 
> -> It shows Me error, I can't find readme also how can i run into this in Browser, In Readme there is line -> Go to your application url and kick start it. But which one is URL I don't understand.
> 
> ![image](https://private-user-images.githubusercontent.com/164132206/315273635-295c98cc-c245-439b-9204-4cbea3e03a57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDA4MDcsIm5iZiI6MTcxMzgwMDUwNywicGF0aCI6Ii8xNjQxMzIyMDYvMzE1MjczNjM1LTI5NWM5OGNjLWMyNDUtNDM5Yi05MjA0LTRjYmVhM2UwM2E1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxNTQxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTJiODYzYzYxY2MwZTQzYzIyMjY2MWZkOGNjMjM3MmJlMGU1YzNhYmJlYTViNTg1ZGJhZDUxYjFkM2YyMmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uvWNWIVQit6UpWz1dWjU6U3pk4j4WdFImvZjTmkJ7NI)

Sorry for the late reply? Did you later got it solved?

**Comment by maskmeta451** [comment]
No, The issue is not solved. I cannot run the project.

**Comment by mitmelon** [comment]
> No, The issue is not solved. I cannot run the project.

What time do you think will be right for you so I can send you a Google meet link to screen share your screen for assistance?
